import * as Auth from "./Auth"
import * as Resto from "./Resto"
import * as Warung from "./Warung"
import * as Pedagang from "./Pedagang"
import * as Motoris from "./Motoris"
import * as Komunitas from "./Komunitas"
import * as Profile from "./Profile"

export { Auth, Resto, Warung, Pedagang, Motoris, Komunitas, Profile }
export { default as Loading } from "./Loading"
export { default as Dashboard } from "./Dashboard"
export { default as Success } from "./Success"
export { default as PinMap } from "./PinMap"
export { default as EditSchedule } from "./EditSchedule"
export { default as EditMenuDiscount } from "./EditMenuDiscount"
export { default as OTP } from "./OTP"
// export { default as OrderDetail } from "./OrderDetail"
