import * as Setup from "./Setup"

export { Setup }
export { default as Dashboard } from "./Dashboard"
export { default as Profile } from "./Profile"
export { default as DataPribadi } from "./DataPribadi"
export { default as Alamat } from "./Alamat"
export { default as AlamatSingle } from "./AlamatSingle"
export { default as Jadwal } from "./Jadwal"
export { default as MenuTersedia } from "./MenuTersedia"
export { default as MenuHabis } from "./MenuHabis"
export { default as MenuForm } from "./MenuForm"
export { default as CairkanSaldo } from "./CairkanSaldo"
export { default as Promo } from "./Promo"
export { default as Preview } from "./Preview"
export { default as PreviewDetail } from "./PreviewDetail"
export { default as PesananBaru } from "./PesananBaru"
export { default as PesananProses } from "./PesananProses"
export { default as PesananDetail } from "./PesananDetail"
export { default as PesananTolak } from "./PesananTolak"
export { default as History } from "./History"
export { default as CategoryList } from "./CategoryList"
export { default as CategoryAdd } from "./CategoryAdd"
